services:
  api:
    container_name: extract-text-prod
    command: uvicorn app.main:app --host 0.0.0.0 --port ${API_PORT:-7555} --workers ${WORKERS:-9}
    restart: always
    env_file:
      - .env 