services:
  api:
    container_name: extract-text-prod
    command: >
      sh -c "
        CALCULATED_WORKERS=$$(expr 2 \* $${CPU_CORES:-4} + 1);
        exec uvicorn app.main:app --host 0.0.0.0 --port $${API_PORT:-7555} --workers $${WORKERS:-$$CALCULATED_WORKERS}
      "
    restart: always
    env_file:
      - .env 