services:
  api:
    build: .
    container_name: extract-text-dev
    command: uvicorn app.main:app --host 0.0.0.0 --port ${API_PORT:-7555} --workers ${WORKERS:-1} --reload
    ports:
      - "7555:7555"
    env_file:
      - .env
    
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    volumes:
      # Горячая перезагрузка для режима разработки
      - ./app:/code/app
      - ./tests:/code/tests
    
    # Проверка здоровья
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7555/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 