version: '3.8'
services:
  api:
    image: text-extraction-api:latest
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port ${API_PORT:-7555} --reload
    ports:
      - "${API_PORT:-7555}:${API_PORT:-7555}"
    volumes:
      - ./app:/code/app
      - ./tests:/code/tests
    env_file:
      - .env
    environment:
      - PYTHONPATH=/code 